SELECT 
    l.CODE_GENDER AS local_CODE_GENDER,
    g.CODE_GENDER AS gcp_CODE_GENDER,
    CASE WHEN l.CODE_GENDER != g.CODE_GENDER THEN 'Diferença' ELSE 'Igual' END AS CODE_GENDER_DIFF,    
    l.AMT_INCOME_TOTAL AS local_AMT_INCOME_TOTAL,
    g.AMT_INCOME_TOTAL AS gcp_AMT_INCOME_TOTAL,
    CASE WHEN l.AMT_INCOME_TOTAL != g.AMT_INCOME_TOTAL THEN 'Diferença' ELSE 'Igual' END AS AMT_INCOME_TOTAL_DIFF,          
    l.DAYS_BIRTH AS local_DAYS_BIRTH,
    g.DAYS_BIRTH AS gcp_DAYS_BIRTH,
    CASE WHEN l.DAYS_BIRTH != g.DAYS_BIRTH THEN 'Diferença' ELSE 'Igual' END AS DAYS_BIRTH_DIFF,      
    l.FLAG_WORK_PHONE AS local_FLAG_WORK_PHONE,
    g.FLAG_WORK_PHONE AS gcp_FLAG_WORK_PHONE,
    CASE WHEN l.FLAG_WORK_PHONE != g.FLAG_WORK_PHONE THEN 'Diferença' ELSE 'Igual' END AS FLAG_WORK_PHONE_DIFF,    
    l.OCCUPATION_TYPE AS local_OCCUPATION_TYPE,
    g.OCCUPATION_TYPE AS gcp_OCCUPATION_TYPE,
    CASE WHEN l.OCCUPATION_TYPE != g.OCCUPATION_TYPE THEN 'Diferença' ELSE 'Igual' END AS OCCUPATION_TYPE_DIFF
FROM application_record_local l
JOIN application_record_gcp g ON l.ID = g.ID;