WITH Duplicados_Locais AS (
    SELECT ID
    FROM application_record_local
    GROUP BY ID
    HAVING COUNT(*) > 1
),
Duplicados_GCP AS (
    SELECT ID
    FROM application_record_gcp
    GROUP BY ID
    HAVING COUNT(*) > 1
),
Registros_Em_Ambas AS (
    SELECT l.ID
    FROM application_record_local l
    JOIN application_record_gcp g ON l.ID = g.ID
),
Registros_Apenas_Locais AS (
    SELECT ID
    FROM application_record_local
    WHERE ID NOT IN (SELECT ID FROM application_record_gcp)
),
Registros_Apenas_GCP AS (
    SELECT ID
    FROM application_record_gcp
    WHERE ID NOT IN (SELECT ID FROM application_record_local)
)

SELECT 
    (SELECT COUNT(*) FROM Duplicados_Locais) AS Duplicados_Locais,
    (SELECT COUNT(*) FROM Duplicados_GCP) AS Duplicados_GCP,
    (SELECT COUNT(*) FROM Registros_Em_Ambas) AS Ambos,
    (SELECT COUNT(*) FROM Registros_Apenas_Locais) AS Apenas_Locais,
    (SELECT COUNT(*) FROM Registros_Apenas_GCP) AS Apenas_GCP;



-- Comparação das colunas
SELECT 
    SUM(CASE WHEN l.CODE_GENDER = g.CODE_GENDER THEN 1 ELSE 0 END) AS CODE_GENDER_Igual,
    SUM(CASE WHEN l.CODE_GENDER != g.CODE_GENDER THEN 1 ELSE 0 END) AS CODE_GENDER_Diferenca,
    SUM(CASE WHEN l.FLAG_OWN_CAR = g.FLAG_OWN_CAR THEN 1 ELSE 0 END) AS FLAG_OWN_CAR_Igual,
    SUM(CASE WHEN l.FLAG_OWN_CAR != g.FLAG_OWN_CAR THEN 1 ELSE 0 END) AS FLAG_OWN_CAR_Diferenca,
    SUM(CASE WHEN l.FLAG_OWN_REALTY = g.FLAG_OWN_REALTY THEN 1 ELSE 0 END) AS FLAG_OWN_REALTY_Igual,
    SUM(CASE WHEN l.FLAG_OWN_REALTY != g.FLAG_OWN_REALTY THEN 1 ELSE 0 END) AS FLAG_OWN_REALTY_Diferenca,
    SUM(CASE WHEN l.CNT_CHILDREN = g.CNT_CHILDREN THEN 1 ELSE 0 END) AS CNT_CHILDREN_Igual,
    SUM(CASE WHEN l.CNT_CHILDREN != g.CNT_CHILDREN THEN 1 ELSE 0 END) AS CNT_CHILDREN_Diferenca,
    SUM(CASE WHEN l.AMT_INCOME_TOTAL = g.AMT_INCOME_TOTAL THEN 1 ELSE 0 END) AS AMT_INCOME_TOTAL_Igual,
    SUM(CASE WHEN l.AMT_INCOME_TOTAL != g.AMT_INCOME_TOTAL THEN 1 ELSE 0 END) AS AMT_INCOME_TOTAL_Diferenca,
    SUM(CASE WHEN l.NAME_INCOME_TYPE = g.NAME_INCOME_TYPE THEN 1 ELSE 0 END) AS NAME_INCOME_TYPE_Igual,
    SUM(CASE WHEN l.NAME_INCOME_TYPE != g.NAME_INCOME_TYPE THEN 1 ELSE 0 END) AS NAME_INCOME_TYPE_Diferenca,
    SUM(CASE WHEN l.NAME_EDUCATION_TYPE = g.NAME_EDUCATION_TYPE THEN 1 ELSE 0 END) AS NAME_EDUCATION_TYPE_Igual,
    SUM(CASE WHEN l.NAME_EDUCATION_TYPE != g.NAME_EDUCATION_TYPE THEN 1 ELSE 0 END) AS NAME_EDUCATION_TYPE_Diferenca,
    SUM(CASE WHEN l.NAME_FAMILY_STATUS = g.NAME_FAMILY_STATUS THEN 1 ELSE 0 END) AS NAME_FAMILY_STATUS_Igual,
    SUM(CASE WHEN l.NAME_FAMILY_STATUS != g.NAME_FAMILY_STATUS THEN 1 ELSE 0 END) AS NAME_FAMILY_STATUS_Diferenca,
    SUM(CASE WHEN l.NAME_HOUSING_TYPE = g.NAME_HOUSING_TYPE THEN 1 ELSE 0 END) AS NAME_HOUSING_TYPE_Igual,
    SUM(CASE WHEN l.NAME_HOUSING_TYPE != g.NAME_HOUSING_TYPE THEN 1 ELSE 0 END) AS NAME_HOUSING_TYPE_Diferenca,
    SUM(CASE WHEN l.DAYS_BIRTH = g.DAYS_BIRTH THEN 1 ELSE 0 END) AS DAYS_BIRTH_Igual,
    SUM(CASE WHEN l.DAYS_BIRTH != g.DAYS_BIRTH THEN 1 ELSE 0 END) AS DAYS_BIRTH_Diferenca,
    SUM(CASE WHEN l.DAYS_EMPLOYED = g.DAYS_EMPLOYED THEN 1 ELSE 0 END) AS DAYS_EMPLOYED_Igual,
    SUM(CASE WHEN l.DAYS_EMPLOYED != g.DAYS_EMPLOYED THEN 1 ELSE 0 END) AS DAYS_EMPLOYED_Diferenca,
    SUM(CASE WHEN l.FLAG_MOBIL = g.FLAG_MOBIL THEN 1 ELSE 0 END) AS FLAG_MOBIL_Igual,
    SUM(CASE WHEN l.FLAG_MOBIL != g.FLAG_MOBIL THEN 1 ELSE 0 END) AS FLAG_MOBIL_Diferenca,
    SUM(CASE WHEN l.FLAG_WORK_PHONE = g.FLAG_WORK_PHONE THEN 1 ELSE 0 END) AS FLAG_WORK_PHONE_Igual,
    SUM(CASE WHEN l.FLAG_WORK_PHONE != g.FLAG_WORK_PHONE THEN 1 ELSE 0 END) AS FLAG_WORK_PHONE_Diferenca,
    SUM(CASE WHEN l.FLAG_PHONE = g.FLAG_PHONE THEN 1 ELSE 0 END) AS FLAG_PHONE_Igual,
    SUM(CASE WHEN l.FLAG_PHONE != g.FLAG_PHONE THEN 1 ELSE 0 END) AS FLAG_PHONE_Diferenca,
    SUM(CASE WHEN l.FLAG_EMAIL = g.FLAG_EMAIL THEN 1 ELSE 0 END) AS FLAG_EMAIL_Igual,
    SUM(CASE WHEN l.FLAG_EMAIL != g.FLAG_EMAIL THEN 1 ELSE 0 END) AS FLAG_EMAIL_Diferenca,
    SUM(CASE WHEN l.OCCUPATION_TYPE = g.OCCUPATION_TYPE THEN 1 ELSE 0 END) AS OCCUPATION_TYPE_Igual,
    SUM(CASE WHEN l.OCCUPATION_TYPE != g.OCCUPATION_TYPE THEN 1 ELSE 0 END) AS OCCUPATION_TYPE_Diferenca,
    SUM(CASE WHEN l.CNT_FAM_MEMBERS = g.CNT_FAM_MEMBERS THEN 1 ELSE 0 END) AS CNT_FAM_MEMBERS_Igual,
    SUM(CASE WHEN l.CNT_FAM_MEMBERS != g.CNT_FAM_MEMBERS THEN 1 ELSE 0 END) AS CNT_FAM_MEMBERS_Diferenca
FROM 
    application_record_local l
JOIN 
    application_record_gcp g ON l.ID = g.ID;
